### ISSUE TITLE
BubbleKern for Glyphs 3

### ISSUE THREAD

**Issue by gorjious** [Tosche/BubbleKern#4]
Will there be a BubbleKern update for Glyphs 3?

**Comment by schriftgestalt** [comment]
I made it work in Glyphs 3. Please try if it is working as expected.

**Comment by gorjious** [comment]
Here are screenshots of issues:
[BubbleKern3_issues.zip](https://github.com/Tosche/BubbleKern/files/7679494/BubbleKern3_issues.zip)

• Starting up has this note:
```
Note: 'Make Bubble Layers' could not load preferences. Will resort to defaults
Make Bubble Layers Error (fitToSidebearing): list index 30 out of range 30
```
• Nudged and Trimmed options are not working as expected (see images)

• Kern All Pairs and Kern Pairs for Selected Glyphs isn't working either (see images)
`BubbleKern Error (BubbleKernMain): 'GSLayer' object has no attribute 'addPath_'`

•Doesn't allow adding pairs to the list (see images)
`BubbleKern Error (confirmChange): 'GSApplication' object has no attribute 'displayDialog_'`

• Delete Bubble layer script is not working
```
[<GSLayer "bubble" (A)>]
delete
Traceback (most recent call last):
  File "Delete Bubble Layers.py", line 27
    glyph.removeLayerForKey_(bubble.layerId)
AttributeError: 'NSKVONotifying_GSGlyph' object has no attribute 'removeLayerForKey_'
```

• Typo: Adhere to sidebearigs -> Adhere to sidebearings

**Comment by Tosche** [comment]
Just to let you know, I'm working on the fixes.
Make Bubble Layers' fitToSidebearing issue: still working, especially the trimming option. I'll need @schriftgestalt's help with the subtractPath (question posted on the forum).
Make Bubble Layers' typo: fixed.
Delete Bubble Layer: fixed. I'm thinking of merging with the Make script though.
BubbleKern's addPath issue: fixed.
BubbleKern's displayDialog issue: fixed.

**Comment by Tosche** [comment]
All withstanding issues fixed. Now I'm working on the scripts merger, and option to change the bubble colour as a new feature. I'll post the update tomorrow.

**Comment by schriftgestalt** [comment]
I was thinking of putting the scripts inside the plugin. The plugin would add menu items on load. 

This would simplify the installation significantly.

**Comment by BraveType** [comment]
Hello Tosche,
I tried to make it work in Glyphs3,
but I get this error message in the makro window:

NameError: name 'NSMutableDictionary' is not defined
Traceback (most recent call last):
  File "BubbleKern.py", line 54
    favDic = NSMutableDictionary.alloc().initWithDictionary_copyItems_(favDic, True)
NameError: name 'NSMutableDictionary' is not defined

Am I doing something wrong?
Might the problem be that I have MacOs Catalina?

Thank you for your time and best regards from Brave Type.

**Comment by gorjious** [comment]
I had a separate issues that I was going to post but just updated to the latest BubbleKern version and I am getting the same error message. 

I'm on Mojave but everything was working fine a couple versions ago.

**Comment by Tosche** [comment]
Just to let you know that I am working on a new version for Glyphs 3. The core part is working but I want to improve the user experience since it's one plugin and multiple scripts. It's taking time due to other commitments, but a fix will come in the future.

**Comment by gorjious** [comment]
Hi Toshi, just wondering if an update is still in the works. 
If the main part is working, I'd be happy to use that in the meantime.

**Comment by Tosche** [comment]
I haven't been able to work on the supposed big update as much. I think I should just make the current version work for now.

**Comment by schriftgestalt** [comment]
@Tosche Do you like to call me to discus how to best refactor this?

**Comment by Tosche** [comment]
@schriftgestalt Yes please!

**Comment by pedestriantactics** [comment]
Has this been updated to Glyphs 3? I installed this and don't see the make bubble layers automation. Also the run bubble kern command is constantly grayed out.

**Comment by schriftgestalt** [comment]
I have fixed the menu item (an underlying library had changed and broke them).
The rest works fine in Glyphs 3.
